### ISSUE TITLE
Add benchmark action to github actions

### ISSUE THREAD

**Issue by l0k18** [dusk-network/bls12_381-sign-go#13]
**On-demand benchmarking for `bls12_381-sign(-go)?`**
Adding a github action that triggers a benchmark run for this repository.

**Benching on dedicated hardware is better** 
Developer's machines often are busy doing other things like playing youtube videos, running video conferencing and GUI heavy apps like Discord, the IDEs themselves can be quite heavy, and this all leads to a greater variance in benchmark results. Further, the web interface means that anyone can trigger a benchmark on any commit of the repository on any new commit on the repository.

**Describe alternatives you've considered**
Slow hardware and wide variance of results from running it on our dev machines makes benchmarking less effective.

~~**Additional context**~~
~~Add any other context or screenshots about the feature request here.~~

**Comment by herr-seppia** [comment]
Closing as obsolete
