### ISSUE TITLE
Add bls12_381-sign microservice and benchmark to compare cgo to the service

### ISSUE THREAD

**Issue by l0k18** [dusk-network/bls12_381-sign-go#8]
**Describe what you want implemented** 
To enable a complete side by side comparison, first tests and then add the benchmarks so performance between using `bls12_381-sign` via CGO versus running over a gRPC service. For this there will be added a switch to allow using the cgo or to use the rpc and spawn the worker process for the API calls.

**Describe "Why" this is needed**
To ensure that we minimize the bottleneck of the processing of BLS12-381 signatures within the `dusk-blockchain` node. Previously substantial improvements were seen with CGO versus gRPC for similar kinds of services, so this will determine if it is a better option.

**Describe alternatives you've considered**
N/A

**Additional context**
After implementing the IPC inside bls12_381-sign on the microservice branch, all of the code from that branch that will implement the service will be done inside this repository.

**Comment by herr-seppia** [comment]
Closing as obsolete
